import { MOCK_SALON_SESSION } from "@/features/dashboard/mock-data";

import type { SalonService, ServiceStaffMember } from "./types";

export const MOCK_SERVICE_STAFF: ServiceStaffMember[] = [
  { id: "staff_emma", name: "Emma" },
  { id: "staff_sophia", name: "Sophia" },
  { id: "staff_jessica", name: "Jessica" },
  { id: "staff_mia", name: "Mia Park" },
  { id: "staff_alex", name: "Alex Kim" },
];

function staffFor(ids: string[]): ServiceStaffMember[] {
  return MOCK_SERVICE_STAFF.filter((s) => ids.includes(s.id));
}

const salonId = MOCK_SALON_SESSION.salonId;
const now = "2026-08-06T08:00:00.000Z";

export const MOCK_SERVICES: SalonService[] = [
  {
    id: "svc_womens_cut",
    salonId,
    name: "Women's Cut",
    category: "Hair Cut",
    description: "Consultation, wash, precision cut, and finish.",
    duration: 60,
    price: 95,
    priceMax: null,
    priceType: "fixed",
    staffIds: ["staff_emma", "staff_sophia", "staff_jessica"],
    staff: staffFor(["staff_emma", "staff_sophia", "staff_jessica"]),
    displayOrder: 1,
    status: "active",
    featured: true,
    bookingEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "svc_mens_cut",
    salonId,
    name: "Men's Cut & Style",
    category: "Hair Cut",
    description: "Classic or modern cut with style finish.",
    duration: 45,
    price: 65,
    priceMax: null,
    priceType: "fixed",
    staffIds: ["staff_alex", "staff_emma"],
    staff: staffFor(["staff_alex", "staff_emma"]),
    displayOrder: 2,
    status: "active",
    featured: false,
    bookingEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "svc_balayage",
    salonId,
    name: "Balayage",
    category: "Hair Colour",
    description: "Hand-painted colour with toner and treatment.",
    duration: 180,
    price: 280,
    priceMax: 380,
    priceType: "range",
    staffIds: ["staff_sophia", "staff_mia"],
    staff: staffFor(["staff_sophia", "staff_mia"]),
    displayOrder: 3,
    status: "active",
    featured: true,
    bookingEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "svc_colour_refresh",
    salonId,
    name: "Colour Refresh",
    category: "Hair Colour",
    description: "Root touch-up or gloss refresh.",
    duration: 90,
    price: 145,
    priceMax: null,
    priceType: "from",
    staffIds: ["staff_mia", "staff_jessica"],
    staff: staffFor(["staff_mia", "staff_jessica"]),
    displayOrder: 4,
    status: "active",
    featured: false,
    bookingEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "svc_keratin",
    salonId,
    name: "Keratin Treatment",
    category: "Treatment",
    description: "Smoothing treatment for frizz control lasting weeks.",
    duration: 150,
    price: 320,
    priceMax: null,
    priceType: "fixed",
    staffIds: ["staff_mia"],
    staff: staffFor(["staff_mia"]),
    displayOrder: 5,
    status: "active",
    featured: false,
    bookingEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "svc_blowdry",
    salonId,
    name: "Blow Dry",
    category: "Styling",
    description: "Wash and professional blow dry finish.",
    duration: 45,
    price: 55,
    priceMax: null,
    priceType: "fixed",
    staffIds: ["staff_sophia", "staff_jessica", "staff_emma"],
    staff: staffFor(["staff_sophia", "staff_jessica", "staff_emma"]),
    displayOrder: 6,
    status: "active",
    featured: false,
    bookingEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "svc_kids",
    salonId,
    name: "Kids Cut",
    category: "Kids",
    description: "Gentle cut for under 12.",
    duration: 30,
    price: 40,
    priceMax: null,
    priceType: "fixed",
    staffIds: ["staff_emma", "staff_alex"],
    staff: staffFor(["staff_emma", "staff_alex"]),
    displayOrder: 7,
    status: "inactive",
    featured: false,
    bookingEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "svc_consult",
    salonId,
    name: "Colour Consultation",
    category: "Consultation",
    description: "In-person colour plan before a major change.",
    duration: 30,
    price: 0,
    priceMax: null,
    priceType: "fixed",
    staffIds: ["staff_mia", "staff_sophia"],
    staff: staffFor(["staff_mia", "staff_sophia"]),
    displayOrder: 8,
    status: "active",
    featured: false,
    bookingEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
];
