export type BookingUiLocale = "en" | "ko";

export function bookingWizardCopy(locale: BookingUiLocale) {
  if (locale === "ko") {
    return {
      backToSalon: "← 업체로",
      book: "예약",
      intro: "서비스와 시간을 고르면 영업시간·휴가·버퍼를 반영한 가능한 시간이 나옵니다.",
      steps: [
        { id: "service" as const, label: "서비스 선택" },
        { id: "staff" as const, label: "담당자 선택" },
        { id: "date" as const, label: "날짜 선택" },
        { id: "time" as const, label: "시간 선택" },
        { id: "customer" as const, label: "예약자 정보" },
        { id: "summary" as const, label: "예약 확인" },
      ],
      selectService: "서비스 선택",
      selectStaff: "담당자 선택",
      noStaff: "이 서비스를 예약할 수 있는 담당자가 없습니다.",
      selectDate: "날짜 선택",
      selectTime: "시간 선택",
      minutes: "분",
      yourDetails: "예약자 정보",
      summary: "예약 확인",
      confirmInstant: "예약이 바로 확정됩니다.",
      confirmPending: "샵이 확인할 때까지 예약은 대기 상태입니다.",
      back: "이전",
      continue: "다음",
      confirming: "예약 중…",
      confirmBooking: "예약 확인",
      chooseService: "서비스를 선택해 주세요.",
      chooseStaff: "담당자를 선택해 주세요.",
      chooseDate: "날짜를 선택해 주세요.",
      dateUnavailable: "그날은 예약할 수 없습니다.",
      chooseTime: "시간을 선택해 주세요.",
      nameRequired: "이름과 성을 입력해 주세요.",
      phoneRequired: "전화번호를 입력해 주세요.",
      acceptPolicy: "예약 정책에 동의해 주세요.",
      bookFailed: "예약하지 못했습니다.",
      noPreference: "상관없음",
      noPreferenceHint: "가능한 담당자 우선",
      any: "아무나",
      noServices: "예약 가능한 서비스가 아직 없습니다.",
      noTimes: "이날 가능한 시간이 없습니다.",
      firstName: "이름",
      lastName: "성",
      phone: "전화번호",
      notes: "메모",
      policies: "정책",
      bookingPolicy: "예약 정책",
      cancellationPolicy: "취소 정책",
      depositPolicy: "예약금 정책",
      refundPolicy: "환불 정책",
      noShowPolicy: "노쇼 정책",
      acceptPolicies: "예약 정책 동의",
      loadingPolicies: "예약 정책을 불러오는 중…",
      summaryTitle: "예약 확인",
      labelService: "서비스",
      labelStaff: "담당자",
      labelDate: "날짜",
      labelTime: "시간",
      labelDuration: "소요 시간",
      labelPrice: "가격",
      labelName: "이름",
      labelEmail: "이메일",
      labelPhone: "전화번호",
      successTitle: "예약 완료",
      status: "상태",
      done: "완료",
      dateLocale: "ko-KR" as const,
    };
  }

  return {
    backToSalon: "← Back to salon",
    book: "Book",
    intro: "Book a service — available times respect hours, leave, and buffers.",
    steps: [
      { id: "service" as const, label: "Service" },
      { id: "staff" as const, label: "Staff" },
      { id: "date" as const, label: "Date" },
      { id: "time" as const, label: "Time" },
      { id: "customer" as const, label: "Details" },
      { id: "summary" as const, label: "Confirm" },
    ],
    selectService: "Select service",
    selectStaff: "Select staff",
    noStaff: "No available staff for this service.",
    selectDate: "Select date",
    selectTime: "Select time",
    minutes: "min",
    yourDetails: "Your details",
    summary: "Booking summary",
    confirmInstant: "Your booking will be confirmed instantly.",
    confirmPending:
      "Your booking is held as pending until the salon confirms.",
    back: "Back",
    continue: "Continue",
    confirming: "Booking…",
    confirmBooking: "Confirm booking",
    chooseService: "Choose a service.",
    chooseStaff: "Choose staff.",
    chooseDate: "Choose a date.",
    dateUnavailable: "That date is not available.",
    chooseTime: "Choose a time.",
    nameRequired: "First and last name are required.",
    phoneRequired: "Phone is required.",
    acceptPolicy: "Please accept the booking policies to continue.",
    bookFailed: "Could not book.",
    noPreference: "No preference",
    noPreferenceHint: "First available stylist",
    any: "Any",
    noServices: "No bookable services yet.",
    noTimes: "No available times on this day.",
    firstName: "First name *",
    lastName: "Last name *",
    phone: "Phone *",
    notes: "Notes",
    policies: "Policies",
    bookingPolicy: "Booking policy",
    cancellationPolicy: "Cancellation policy",
    depositPolicy: "Deposit policy",
    refundPolicy: "Refund policy",
    noShowPolicy: "No-show policy",
    acceptPolicies:
      "I have read and accept the booking, cancellation, deposit, and refund policies for this appointment.",
    loadingPolicies: "Loading booking policies…",
    summaryTitle: "Booking summary",
    labelService: "Service",
    labelStaff: "Staff",
    labelDate: "Date",
    labelTime: "Time",
    labelDuration: "Duration",
    labelPrice: "Price",
    labelName: "Name",
    labelEmail: "Email",
    labelPhone: "Phone",
    successTitle: "Booking requested",
    status: "Status",
    done: "Done",
    dateLocale: "en-AU" as const,
  };
}

export type BookingWizardCopy = ReturnType<typeof bookingWizardCopy>;
