import type { AdminStaffRow } from "../types";

export const mockStaffList: AdminStaffRow[] = [
  {
    id: "staff-001",
    name: "Emma Chen",
    status: "active",
    presence: "in_service",
    currentRoomName: "Room 2",
    workingToday: true,
    shiftLabel: "9:00 AM – 5:00 PM",
    nextBooking: "Today, 2:30 PM",
  },
  {
    id: "staff-002",
    name: "Sophia Lee",
    status: "active",
    presence: "online",
    currentRoomName: null,
    workingToday: true,
    shiftLabel: "12:00 PM – 9:00 PM",
    nextBooking: "Today, 4:00 PM",
  },
  {
    id: "staff-003",
    name: "Mia Rodriguez",
    status: "on_leave",
    presence: "offline",
    currentRoomName: null,
    workingToday: false,
    shiftLabel: null,
    nextBooking: null,
  },
  {
    id: "staff-004",
    name: "Olivia Park",
    status: "active",
    presence: "offline",
    currentRoomName: null,
    workingToday: false,
    shiftLabel: null,
    nextBooking: "Tomorrow, 10:00 AM",
  },
  {
    id: "staff-005",
    name: "Isabella Nguyen",
    status: "inactive",
    presence: "offline",
    currentRoomName: null,
    workingToday: false,
    shiftLabel: null,
    nextBooking: null,
  },
  {
    id: "staff-006",
    name: "Charlotte Williams",
    status: "active",
    presence: "online",
    currentRoomName: null,
    workingToday: true,
    shiftLabel: "10:00 AM – 6:00 PM",
    nextBooking: "Today, 11:15 AM",
  },
];
