import { MOCK_SALON_SESSION } from "@/features/dashboard/mock-data";

import type {
  SalonCustomer,
  CustomerStatistics,
} from "./types";

const salonId = MOCK_SALON_SESSION.salonId;
const now = "2026-08-06T10:00:00.000Z";

function stats(partial: Partial<CustomerStatistics>): CustomerStatistics {
  return {
    totalBookings: 0,
    completedBookings: 0,
    cancelledBookings: 0,
    totalSpent: 0,
    averageSpent: 0,
    lastVisit: null,
    nextBooking: null,
    preferredStaffId: null,
    preferredStaffName: null,
    favoriteServiceId: null,
    favoriteServiceName: null,
    ...partial,
  };
}

export const MOCK_CUSTOMERS: SalonCustomer[] = [
  {
    id: "cust_emily",
    salonId,
    firstName: "Emily",
    lastName: "Watson",
    fullName: "Emily Watson",
    phone: "0412 345 678",
    email: "emily.watson@email.com",
    birthday: "1992-03-14",
    gender: "female",
    avatar: null,
    status: "vip",
    joinedAt: "2025-01-12T00:00:00.000Z",
    updatedAt: now,
    tags: ["VIP", "Colour Client"],
    loyaltyPoints: 420,
    statistics: stats({
      totalBookings: 18,
      completedBookings: 16,
      cancelledBookings: 1,
      totalSpent: 4280,
      averageSpent: 268,
      lastVisit: "2026-08-06",
      nextBooking: "2026-08-20",
      preferredStaffId: "staff_mia",
      preferredStaffName: "Mia Park",
      favoriteServiceId: "svc_balayage",
      favoriteServiceName: "Balayage",
    }),
    favouriteServices: ["Balayage", "Women's Cut"],
    notes: [
      {
        id: "note_emily_1",
        customerId: "cust_emily",
        staffId: "staff_mia",
        staffName: "Mia Park",
        note: "Prefers cool tones. Sensitive scalp — use gentle shampoo.",
        createdAt: "2026-07-01T04:00:00.000Z",
      },
    ],
    timeline: [
      {
        id: "tl_emily_1",
        customerId: "cust_emily",
        eventType: "booking_completed",
        title: "Booking completed",
        detail: "Balayage with Mia Park",
        bookingId: "bk_1001",
        createdAt: "2026-08-06T01:00:00.000Z",
      },
      {
        id: "tl_emily_2",
        customerId: "cust_emily",
        eventType: "payment_completed",
        title: "Payment completed",
        detail: "$280",
        bookingId: "bk_1001",
        createdAt: "2026-08-06T01:05:00.000Z",
      },
      {
        id: "tl_emily_3",
        customerId: "cust_emily",
        eventType: "review_submitted",
        title: "Review submitted",
        detail: "5★ — “Incredible balayage.”",
        bookingId: null,
        createdAt: "2026-08-06T08:00:00.000Z",
      },
    ],
    media: [
      {
        id: "media_emily_1",
        url: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=400&q=80",
        mediaType: "before",
        caption: "Before colour",
        createdAt: "2026-06-01T00:00:00.000Z",
      },
      {
        id: "media_emily_2",
        url: "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&w=400&q=80",
        mediaType: "after",
        caption: "After balayage",
        createdAt: "2026-06-01T01:00:00.000Z",
      },
    ],
    bookingHistory: [
      {
        id: "bk_1001",
        serviceName: "Balayage + Cut",
        staffName: "Mia Park",
        bookingDate: "2026-08-06",
        startTime: "09:00",
        status: "completed",
        amount: 280,
      },
      {
        id: "bk_0901",
        serviceName: "Colour Refresh",
        staffName: "Mia Park",
        bookingDate: "2026-07-02",
        startTime: "11:00",
        status: "completed",
        amount: 145,
      },
    ],
    upcomingBookings: [
      {
        id: "bk_2001",
        serviceName: "Full Colour",
        staffName: "Mia Park",
        bookingDate: "2026-08-20",
        startTime: "10:00",
        status: "confirmed",
        amount: 210,
      },
    ],
    cancelledBookings: [
      {
        id: "bk_0801",
        serviceName: "Blow Dry",
        staffName: "Sophia",
        bookingDate: "2026-05-10",
        startTime: "14:00",
        status: "cancelled",
        amount: 55,
      },
    ],
  },
  {
    id: "cust_james",
    salonId,
    firstName: "James",
    lastName: "Oliver",
    fullName: "James Oliver",
    phone: "0423 111 222",
    email: "james.oliver@email.com",
    birthday: "1988-11-02",
    gender: "male",
    avatar: null,
    status: "regular",
    joinedAt: "2025-06-20T00:00:00.000Z",
    updatedAt: now,
    tags: ["Monthly Client"],
    loyaltyPoints: 90,
    statistics: stats({
      totalBookings: 6,
      completedBookings: 5,
      cancelledBookings: 0,
      totalSpent: 390,
      averageSpent: 78,
      lastVisit: "2026-08-06",
      nextBooking: "2026-09-03",
      preferredStaffId: "staff_alex",
      preferredStaffName: "Alex Kim",
      favoriteServiceId: "svc_mens_cut",
      favoriteServiceName: "Men's Cut & Style",
    }),
    favouriteServices: ["Men's Cut & Style"],
    notes: [],
    timeline: [
      {
        id: "tl_james_1",
        customerId: "cust_james",
        eventType: "booking_created",
        title: "Booking created",
        detail: "Men's Cut & Style with Alex Kim",
        bookingId: "bk_1002",
        createdAt: "2026-08-05T02:00:00.000Z",
      },
    ],
    media: [],
    bookingHistory: [
      {
        id: "bk_1002",
        serviceName: "Men's Cut & Style",
        staffName: "Alex Kim",
        bookingDate: "2026-08-06",
        startTime: "09:30",
        status: "confirmed",
        amount: 65,
      },
    ],
    upcomingBookings: [
      {
        id: "bk_2101",
        serviceName: "Men's Cut & Style",
        staffName: "Alex Kim",
        bookingDate: "2026-09-03",
        startTime: "10:00",
        status: "confirmed",
        amount: 65,
      },
    ],
    cancelledBookings: [],
  },
  {
    id: "cust_priya",
    salonId,
    firstName: "Priya",
    lastName: "Nair",
    fullName: "Priya Nair",
    phone: "0433 555 777",
    email: "priya.nair@email.com",
    birthday: null,
    gender: "female",
    avatar: null,
    status: "regular",
    joinedAt: "2025-09-01T00:00:00.000Z",
    updatedAt: now,
    tags: ["Student", "Weekly Client"],
    loyaltyPoints: 150,
    statistics: stats({
      totalBookings: 11,
      completedBookings: 10,
      cancelledBookings: 1,
      totalSpent: 1980,
      averageSpent: 198,
      lastVisit: "2026-07-28",
      nextBooking: "2026-08-07",
      preferredStaffId: "staff_mia",
      preferredStaffName: "Mia Park",
      favoriteServiceId: "svc_keratin",
      favoriteServiceName: "Keratin Treatment",
    }),
    favouriteServices: ["Keratin Treatment", "Blow Dry"],
    notes: [
      {
        id: "note_priya_1",
        customerId: "cust_priya",
        staffId: "staff_emma",
        staffName: "Emma",
        note: "Student discount applied. Prefers afternoon appointments.",
        createdAt: "2026-04-12T03:00:00.000Z",
      },
    ],
    timeline: [
      {
        id: "tl_priya_1",
        customerId: "cust_priya",
        eventType: "booking_created",
        title: "Booking created",
        detail: "Keratin Treatment",
        bookingId: "bk_1003",
        createdAt: "2026-08-04T01:00:00.000Z",
      },
    ],
    media: [],
    bookingHistory: [
      {
        id: "bk_0701",
        serviceName: "Keratin Treatment",
        staffName: "Mia Park",
        bookingDate: "2026-07-28",
        startTime: "13:00",
        status: "completed",
        amount: 320,
      },
    ],
    upcomingBookings: [
      {
        id: "bk_1003",
        serviceName: "Keratin Treatment",
        staffName: "Mia Park",
        bookingDate: "2026-08-07",
        startTime: "10:30",
        status: "confirmed",
        amount: 320,
      },
    ],
    cancelledBookings: [],
  },
  {
    id: "cust_hannah",
    salonId,
    firstName: "Hannah",
    lastName: "Lee",
    fullName: "Hannah Lee",
    phone: "0400 888 999",
    email: "hannah.lee@email.com",
    birthday: "1999-07-21",
    gender: "female",
    avatar: null,
    status: "inactive",
    joinedAt: "2024-11-05T00:00:00.000Z",
    updatedAt: now,
    tags: ["Senior"],
    loyaltyPoints: 20,
    statistics: stats({
      totalBookings: 3,
      completedBookings: 2,
      cancelledBookings: 1,
      totalSpent: 150,
      averageSpent: 75,
      lastVisit: "2026-02-14",
      nextBooking: null,
      preferredStaffId: "staff_sophia",
      preferredStaffName: "Sophia",
      favoriteServiceId: "svc_blowdry",
      favoriteServiceName: "Blow Dry",
    }),
    favouriteServices: ["Blow Dry"],
    notes: [],
    timeline: [
      {
        id: "tl_hannah_1",
        customerId: "cust_hannah",
        eventType: "booking_cancelled",
        title: "Booking cancelled",
        detail: "Blow Dry — no-show follow-up",
        bookingId: "bk_1004",
        createdAt: "2026-03-01T00:00:00.000Z",
      },
    ],
    media: [],
    bookingHistory: [],
    upcomingBookings: [],
    cancelledBookings: [
      {
        id: "bk_1004",
        serviceName: "Blow Dry",
        staffName: "Sofia Reyes",
        bookingDate: "2026-03-01",
        startTime: "11:00",
        status: "cancelled",
        amount: 55,
      },
    ],
  },
  {
    id: "cust_daniel",
    salonId,
    firstName: "Daniel",
    lastName: "Brooks",
    fullName: "Daniel Brooks",
    phone: "0411 222 333",
    email: "daniel.brooks@email.com",
    birthday: null,
    gender: "male",
    avatar: null,
    status: "blocked",
    joinedAt: "2025-03-18T00:00:00.000Z",
    updatedAt: now,
    tags: [],
    loyaltyPoints: 0,
    statistics: stats({
      totalBookings: 4,
      completedBookings: 1,
      cancelledBookings: 3,
      totalSpent: 65,
      averageSpent: 65,
      lastVisit: "2025-12-01",
      nextBooking: null,
      preferredStaffId: null,
      preferredStaffName: null,
      favoriteServiceId: null,
      favoriteServiceName: null,
    }),
    favouriteServices: [],
    notes: [
      {
        id: "note_daniel_1",
        customerId: "cust_daniel",
        staffId: null,
        staffName: null,
        note: "Repeated late cancellations. Blocked pending owner review.",
        createdAt: "2026-01-15T00:00:00.000Z",
      },
    ],
    timeline: [
      {
        id: "tl_daniel_1",
        customerId: "cust_daniel",
        eventType: "status_changed",
        title: "Status changed",
        detail: "Marked as blocked",
        bookingId: null,
        createdAt: "2026-01-15T00:00:00.000Z",
      },
    ],
    media: [],
    bookingHistory: [],
    upcomingBookings: [],
    cancelledBookings: [],
  },
];
