import type { Salon, SearchFilterChip } from "./types";

export const SEARCH_FILTER_CHIPS: SearchFilterChip[] = [
  "Hair",
  "Nails",
  "Spa",
  "Massage",
  "Facial",
  "Waxing",
  "Brows",
  "Open Now",
  "Top Rated",
];

/** Temporary mock marketplace data — replace with Supabase later. */
export const MOCK_SALONS: Salon[] = [
  {
    id: "1",
    name: "Lumina Hair Studio",
    logoInitials: "LH",
    logoColor: "#6B5CF6",
    coverGradient: "from-[#EDE9FE] via-[#F5F3FF] to-[#FCE7F3]",
    rating: 4.9,
    reviewCount: 312,
    address: "142 Gympie Rd",
    suburb: "Aspley QLD",
    distanceKm: 0.8,
    isOpen: true,
    availableToday: true,
    tags: ["Hair", "Brows"],
    startingPrice: 65,
    mapX: 42,
    mapY: 38,
  },
  {
    id: "2",
    name: "Bloom Nail Atelier",
    logoInitials: "BN",
    logoColor: "#EC4899",
    coverGradient: "from-[#FCE7F3] via-[#FDF2F8] to-[#EEF2FF]",
    rating: 4.8,
    reviewCount: 198,
    address: "18 Hamilton Rd",
    suburb: "Chermside QLD",
    distanceKm: 1.4,
    isOpen: true,
    availableToday: true,
    tags: ["Nails", "Waxing"],
    startingPrice: 45,
    mapX: 58,
    mapY: 48,
  },
  {
    id: "3",
    name: "Sora Day Spa",
    logoInitials: "SD",
    logoColor: "#0EA5E9",
    coverGradient: "from-[#E0F2FE] via-[#F0F9FF] to-[#EEF2FF]",
    rating: 4.7,
    reviewCount: 256,
    address: "7 Mains Rd",
    suburb: "Sunnybank QLD",
    distanceKm: 2.1,
    isOpen: true,
    availableToday: false,
    tags: ["Spa", "Massage", "Facial"],
    startingPrice: 99,
    mapX: 28,
    mapY: 55,
  },
  {
    id: "4",
    name: "Velvet Brow Bar",
    logoInitials: "VB",
    logoColor: "#8B5CF6",
    coverGradient: "from-[#EDE9FE] via-[#FAF5FF] to-[#F5F3FF]",
    rating: 4.6,
    reviewCount: 141,
    address: "55 Indooroopilly SC",
    suburb: "Indooroopilly QLD",
    distanceKm: 3.2,
    isOpen: false,
    availableToday: true,
    tags: ["Brows", "Waxing"],
    startingPrice: 35,
    mapX: 35,
    mapY: 72,
  },
  {
    id: "5",
    name: "Maison Colour",
    logoInitials: "MC",
    logoColor: "#F59E0B",
    coverGradient: "from-[#FEF3C7] via-[#FFFBEB] to-[#F5F3FF]",
    rating: 4.9,
    reviewCount: 427,
    address: "120 Creek Rd",
    suburb: "Carindale QLD",
    distanceKm: 5.6,
    isOpen: true,
    availableToday: true,
    tags: ["Hair"],
    startingPrice: 120,
    mapX: 78,
    mapY: 32,
  },
  {
    id: "6",
    name: "Quiet Hands Massage",
    logoInitials: "QH",
    logoColor: "#10B981",
    coverGradient: "from-[#D1FAE5] via-[#ECFDF5] to-[#EEF2FF]",
    rating: 4.8,
    reviewCount: 89,
    address: "3 Brunswick St",
    suburb: "New Farm QLD",
    distanceKm: 1.9,
    isOpen: true,
    availableToday: true,
    tags: ["Massage", "Spa"],
    startingPrice: 85,
    mapX: 48,
    mapY: 60,
  },
  {
    id: "7",
    name: "Pearl Facial Lab",
    logoInitials: "PF",
    logoColor: "#6366F1",
    coverGradient: "from-[#E0E7FF] via-[#EEF2FF] to-[#F5F3FF]",
    rating: 4.5,
    reviewCount: 167,
    address: "88 Latrobe Tce",
    suburb: "Paddington QLD",
    distanceKm: 2.8,
    isOpen: false,
    availableToday: false,
    tags: ["Facial", "Spa"],
    startingPrice: 75,
    mapX: 52,
    mapY: 22,
  },
  {
    id: "8",
    name: "Atelier Wax & Glow",
    logoInitials: "AW",
    logoColor: "#DB2777",
    coverGradient: "from-[#FCE7F3] via-[#FFF1F2] to-[#F5F3FF]",
    rating: 4.7,
    reviewCount: 203,
    address: "14 Aspley Hypermarket",
    suburb: "Aspley QLD",
    distanceKm: 1.1,
    isOpen: true,
    availableToday: true,
    tags: ["Waxing", "Facial", "Brows"],
    startingPrice: 40,
    mapX: 62,
    mapY: 40,
  },
  {
    id: "9",
    name: "Northside Barber Co.",
    logoInitials: "NB",
    logoColor: "#1B1F3B",
    coverGradient: "from-[#E5E7EB] via-[#F3F4F6] to-[#EEF2FF]",
    rating: 4.8,
    reviewCount: 156,
    address: "220 Gympie Rd",
    suburb: "Aspley QLD",
    distanceKm: 0.5,
    isOpen: true,
    availableToday: true,
    tags: ["Hair"],
    startingPrice: 40,
    mapX: 46,
    mapY: 34,
  },
  {
    id: "10",
    name: "Chermside Lash Lounge",
    logoInitials: "CL",
    logoColor: "#A855F7",
    coverGradient: "from-[#F3E8FF] via-[#FAF5FF] to-[#FCE7F3]",
    rating: 4.6,
    reviewCount: 94,
    address: "Westfield Chermside",
    suburb: "Chermside QLD",
    distanceKm: 1.7,
    isOpen: true,
    availableToday: true,
    tags: ["Brows", "Facial"],
    startingPrice: 55,
    mapX: 64,
    mapY: 44,
  },
];
