import type { Salon, SearchFilterChip } from "./types";

export const SEARCH_FILTER_CHIPS: SearchFilterChip[] = [
  "Hair",
  "Nails",
  "Spa",
  "Massage",
  "Facial",
  "Waxing",
  "Brows",
  "Open Now",
  "Top Rated",
];

export const SERVICE_OPTIONS = [
  { value: "all", label: "All services" },
  { value: "haircut", label: "Haircut & styling" },
  { value: "colour", label: "Colour & balayage" },
  { value: "nails", label: "Manicure & pedicure" },
  { value: "massage", label: "Massage" },
  { value: "facial", label: "Facial" },
  { value: "waxing", label: "Waxing" },
  { value: "brows", label: "Brows & lashes" },
] as const;

export const MOCK_SALONS: Salon[] = [
  {
    id: "1",
    name: "Lumina Hair Studio",
    logoInitials: "LH",
    logoColor: "#6B5CF6",
    coverGradient: "from-[#EDE9FE] via-[#F5F3FF] to-[#FCE7F3]",
    rating: 4.9,
    reviewCount: 312,
    address: "42 Crown St, Surry Hills",
    suburb: "Sydney NSW",
    distanceKm: 0.8,
    isOpen: true,
    availableToday: true,
    tags: ["Hair", "Brows"],
    startingPrice: 65,
    mapX: 42,
    mapY: 38,
  },
  {
    id: "2",
    name: "Bloom Nail Atelier",
    logoInitials: "BN",
    logoColor: "#EC4899",
    coverGradient: "from-[#FCE7F3] via-[#FDF2F8] to-[#EEF2FF]",
    rating: 4.8,
    reviewCount: 198,
    address: "18 Oxford St, Paddington",
    suburb: "Sydney NSW",
    distanceKm: 1.4,
    isOpen: true,
    availableToday: true,
    tags: ["Nails", "Waxing"],
    startingPrice: 45,
    mapX: 58,
    mapY: 48,
  },
  {
    id: "3",
    name: "Sora Day Spa",
    logoInitials: "SD",
    logoColor: "#0EA5E9",
    coverGradient: "from-[#E0F2FE] via-[#F0F9FF] to-[#EEF2FF]",
    rating: 4.7,
    reviewCount: 256,
    address: "7 Bridge Rd, Glebe",
    suburb: "Sydney NSW",
    distanceKm: 2.1,
    isOpen: true,
    availableToday: false,
    tags: ["Spa", "Massage", "Facial"],
    startingPrice: 99,
    mapX: 28,
    mapY: 55,
  },
  {
    id: "4",
    name: "Velvet Brow Bar",
    logoInitials: "VB",
    logoColor: "#8B5CF6",
    coverGradient: "from-[#EDE9FE] via-[#FAF5FF] to-[#F5F3FF]",
    rating: 4.6,
    reviewCount: 141,
    address: "55 King St, Newtown",
    suburb: "Sydney NSW",
    distanceKm: 3.2,
    isOpen: false,
    availableToday: true,
    tags: ["Brows", "Waxing"],
    startingPrice: 35,
    mapX: 35,
    mapY: 72,
  },
  {
    id: "5",
    name: "Maison Colour",
    logoInitials: "MC",
    logoColor: "#F59E0B",
    coverGradient: "from-[#FEF3C7] via-[#FFFBEB] to-[#F5F3FF]",
    rating: 4.9,
    reviewCount: 427,
    address: "120 Campbell Pde, Bondi",
    suburb: "Sydney NSW",
    distanceKm: 5.6,
    isOpen: true,
    availableToday: true,
    tags: ["Hair"],
    startingPrice: 120,
    mapX: 78,
    mapY: 32,
  },
  {
    id: "6",
    name: "Quiet Hands Massage",
    logoInitials: "QH",
    logoColor: "#10B981",
    coverGradient: "from-[#D1FAE5] via-[#ECFDF5] to-[#EEF2FF]",
    rating: 4.8,
    reviewCount: 89,
    address: "3 Harris St, Pyrmont",
    suburb: "Sydney NSW",
    distanceKm: 1.9,
    isOpen: true,
    availableToday: true,
    tags: ["Massage", "Spa"],
    startingPrice: 85,
    mapX: 48,
    mapY: 60,
  },
  {
    id: "7",
    name: "Pearl Facial Lab",
    logoInitials: "PF",
    logoColor: "#6366F1",
    coverGradient: "from-[#E0E7FF] via-[#EEF2FF] to-[#F5F3FF]",
    rating: 4.5,
    reviewCount: 167,
    address: "88 George St, The Rocks",
    suburb: "Sydney NSW",
    distanceKm: 2.8,
    isOpen: false,
    availableToday: false,
    tags: ["Facial", "Spa"],
    startingPrice: 75,
    mapX: 52,
    mapY: 22,
  },
  {
    id: "8",
    name: "Atelier Wax & Glow",
    logoInitials: "AW",
    logoColor: "#DB2777",
    coverGradient: "from-[#FCE7F3] via-[#FFF1F2] to-[#F5F3FF]",
    rating: 4.7,
    reviewCount: 203,
    address: "14 Darlinghurst Rd, Potts Point",
    suburb: "Sydney NSW",
    distanceKm: 1.1,
    isOpen: true,
    availableToday: true,
    tags: ["Waxing", "Facial", "Brows"],
    startingPrice: 40,
    mapX: 62,
    mapY: 40,
  },
];
