import { MOCK_SALON_SESSION } from "@/features/dashboard/mock-data";
import { MOCK_SERVICES } from "@/features/salon-services/mock-data";

import { defaultWorkingHours } from "./constants";
import type { SalonStaffMember, StaffAssignedService } from "./types";

const salonId = MOCK_SALON_SESSION.salonId;
const now = "2026-08-06T08:00:00.000Z";

function servicesFor(ids: string[]): StaffAssignedService[] {
  return MOCK_SERVICES.filter((s) => ids.includes(s.id)).map((s) => ({
    id: s.id,
    name: s.name,
    category: s.category,
  }));
}

export const MOCK_SALON_STAFF: SalonStaffMember[] = [
  {
    id: "staff_emma",
    salonId,
    firstName: "Emma",
    lastName: "Walsh",
    displayName: "Emma",
    photo: null,
    email: "emma@glowhair.studio",
    phone: "0400 111 001",
    role: "Senior Stylist",
    status: "active",
    experience: 8,
    rating: 4.9,
    languages: ["English", "Mandarin"],
    specialties: ["Cuts", "Colour"],
    bio: "Senior stylist specialising in precision cuts and lived-in colour.",
    instagram: "@emma.hair",
    certificates: ["Certificate III Hairdressing"],
    portfolioImages: [],
    workingHours: defaultWorkingHours(),
    breaks: [0, 1, 2, 3, 4].map((dayOfWeek) => ({
      id: `brk_emma_lunch_${dayOfWeek}`,
      dayOfWeek: dayOfWeek as 0 | 1 | 2 | 3 | 4,
      startTime: "12:00",
      endTime: "13:00",
      breakType: "lunch" as const,
      label: "Lunch",
    })),
    leaves: [],
    serviceIds: ["svc_womens_cut", "svc_balayage", "svc_colour_refresh", "svc_blowdry"],
    services: servicesFor([
      "svc_womens_cut",
      "svc_balayage",
      "svc_colour_refresh",
      "svc_blowdry",
    ]),
    bookingEnabled: true,
    maxDailyBookings: 8,
    maxWeeklyBookings: 35,
    bufferMinutes: 15,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "staff_sophia",
    salonId,
    firstName: "Sophia",
    lastName: "Reyes",
    displayName: "Sophia",
    photo: null,
    email: "sophia@glowhair.studio",
    phone: "0400 111 002",
    role: "Stylist",
    status: "active",
    experience: 5,
    rating: 4.8,
    languages: ["English", "Spanish"],
    specialties: ["Balayage", "Styling"],
    bio: "Colour specialist with a soft, natural finish.",
    instagram: "@sophia.colour",
    certificates: [],
    portfolioImages: [],
    workingHours: defaultWorkingHours().map((d) =>
      d.dayOfWeek === 0 ? { ...d, isDayOff: true } : d,
    ),
    breaks: [
      {
        id: "brk_sophia_coffee",
        dayOfWeek: 1,
        startTime: "11:00",
        endTime: "11:15",
        breakType: "coffee",
        label: "Coffee",
      },
    ],
    leaves: [
      {
        id: "leave_sophia_1",
        startDate: "2026-08-18",
        endDate: "2026-08-20",
        leaveType: "annual",
        reason: "Family trip",
      },
    ],
    serviceIds: ["svc_womens_cut", "svc_balayage", "svc_blowdry", "svc_consult"],
    services: servicesFor([
      "svc_womens_cut",
      "svc_balayage",
      "svc_blowdry",
      "svc_consult",
    ]),
    bookingEnabled: true,
    maxDailyBookings: 7,
    maxWeeklyBookings: 30,
    bufferMinutes: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "staff_jessica",
    salonId,
    firstName: "Jessica",
    lastName: "Nguyen",
    displayName: "Jessica",
    photo: null,
    email: "jessica@glowhair.studio",
    phone: "0400 111 003",
    role: "Junior Stylist",
    status: "active",
    experience: 2,
    rating: 4.7,
    languages: ["English", "Vietnamese"],
    specialties: ["Blow dry", "Kids"],
    bio: "Friendly junior stylist focused on finish and care.",
    instagram: "",
    certificates: [],
    portfolioImages: [],
    workingHours: defaultWorkingHours(),
    breaks: [],
    leaves: [],
    serviceIds: ["svc_womens_cut", "svc_colour_refresh", "svc_blowdry"],
    services: servicesFor([
      "svc_womens_cut",
      "svc_colour_refresh",
      "svc_blowdry",
    ]),
    bookingEnabled: true,
    maxDailyBookings: 6,
    maxWeeklyBookings: 28,
    bufferMinutes: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "staff_mia",
    salonId,
    firstName: "Mia",
    lastName: "Park",
    displayName: "Mia Park",
    photo: null,
    email: "mia@glowhair.studio",
    phone: "0400 111 004",
    role: "Senior Stylist",
    status: "active",
    experience: 10,
    rating: 5.0,
    languages: ["English", "Korean"],
    specialties: ["Keratin", "Colour"],
    bio: "Treatments and transformative colour.",
    instagram: "@miapark.hair",
    certificates: ["Keratin Specialist"],
    portfolioImages: [],
    workingHours: defaultWorkingHours(),
    breaks: [
      {
        id: "brk_mia_lunch",
        dayOfWeek: 2,
        startTime: "12:30",
        endTime: "13:00",
        breakType: "lunch",
        label: "Lunch",
      },
    ],
    leaves: [],
    serviceIds: [
      "svc_balayage",
      "svc_colour_refresh",
      "svc_keratin",
      "svc_consult",
    ],
    services: servicesFor([
      "svc_balayage",
      "svc_colour_refresh",
      "svc_keratin",
      "svc_consult",
    ]),
    bookingEnabled: true,
    maxDailyBookings: 5,
    maxWeeklyBookings: 22,
    bufferMinutes: 20,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "staff_alex",
    salonId,
    firstName: "Alex",
    lastName: "Kim",
    displayName: "Alex Kim",
    photo: null,
    email: "alex@glowhair.studio",
    phone: "0400 111 005",
    role: "Barber",
    status: "inactive",
    experience: 6,
    rating: 4.6,
    languages: ["English"],
    specialties: ["Fades", "Beard"],
    bio: "Modern barbering and classic finishes.",
    instagram: "",
    certificates: [],
    portfolioImages: [],
    workingHours: defaultWorkingHours().map((d) =>
      d.dayOfWeek >= 5 ? { ...d, isDayOff: true } : d,
    ),
    breaks: [],
    leaves: [],
    serviceIds: ["svc_mens_cut", "svc_kids"],
    services: servicesFor(["svc_mens_cut", "svc_kids"]),
    bookingEnabled: false,
    maxDailyBookings: 10,
    maxWeeklyBookings: 40,
    bufferMinutes: 5,
    createdAt: now,
    updatedAt: now,
  },
];

export function getAssignableServices(): StaffAssignedService[] {
  return MOCK_SERVICES.filter((s) => s.status !== "archived").map((s) => ({
    id: s.id,
    name: s.name,
    category: s.category,
  }));
}
